version: "3"

vars:
  EXT: '{{if eq OS "windows"}}.exe{{end}}'

tasks:
  dev:
    cmds:
      - go run cmd/spotify-auto-genius/main.go

  build:
    cmds:
      - go build -o bin/spotify-auto-genius{{.EXT}} -ldflags="-s -w" -gcflags=all="-l -B" ./cmd/spotify-auto-genius/main.go

  run:
    cmds:
      - ./bin/spotify-auto-genius{{.EXT}}

  release-local:
    cmds:
      - goreleaser release --snapshot --clean

  release:
    cmds:
      - goreleaser release

  clean:
    cmds:
      - |
        {{if eq OS "windows"}}
          del bin\spotify-auto-genius{{.EXT}}
        {{else}}
          rm -f bin/spotify-auto-genius{{.EXT}}
        {{end}}
