version: "3"

tasks:
  dev:
    cmds:
      - go run main.go

  build:
    cmds:
      - go build -o bin/spotify-auto-genius.exe -ldflags="-s -w" -gcflags=all="-l -B" ./cmd/spotify-auto-genius/main.go

  run:
    cmds:
      - ./bin/spotify-auto-genius.exe

  clean:
    cmds:
      - rm -f bin/spotify-auto-genius.exe
